### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by zQueal** [nikdoof/bukkitxmpp#5]
I've been desperately trying to find a way to properly install your plugin, however, to no avail.

This server is running CraftBukkit version git-Bukkit-1.2.5-R1.0-b2149jnks (MC: 1.2.5)

I've connected to my VPS via SSH and pulled your .jar file into my plugins directory, done a full reload from the minecraft ssh console, and from in-game using '/reload' and no directories are created and no mention of the plugin being installed when '/pl' is used.

Any idea as to how I could actually get this thing to install?

**Comment by nikdoof** [comment]
BukkitXMPP has fell behind the current API standards for CraftBukkit, so it could be that it doesn't work at all. I'm going to be working on it soon to bring it up to 1.2.5 standard within the next week or so.

**Comment by zQueal** [comment]
Awesome! Sounds great, and thanks for the info!

Just wanted to say, if anyone else is having the same problem, and are in need of an XMPP minecraft bridge, I found an excellent solution in a public Gist by: @lukeledet

Working great! :)
